#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.
set -x  # All executed commands are printed to the terminal

#mv /tmp/contents/static/mozilla.gpg /etc/apt/keyrings/
#mv /tmp/contents/static/mozilla.list /etc/apt/sources.list.d/

aptitude update ; aptitude install -y curl firefox-esr firefox-esr-l10n-es-es openjdk-17-jre libnss3-tools xdg-utils xvfb

useradd -m -u 1000 -p U6aMy0wojraho -G sudo -s /bin/bash user

su user xdg-mime default afirma.desktop x-scheme-handler/afirma
su user xvfb-run firefox &
pid=$!
sleep 5
kill $pid

wget -O /tmp/autofirma.zip 'https://firmaelectronica.gob.es/content/dam/firmaelectronica/descargas-software/autofirma19/Autofirma_Linux_Debian.zip'
wget -O /tmp/fnmt.deb 'https://descargas.cert.fnmt.es/Linux/configuradorfnmt_5.0.3.amd64.deb'

unzip -d /tmp /tmp/autofirma.zip
dpkg -i /tmp/autofirma*.deb

su user xvfb-run autofirma &
pid=$!
sleep 5
kill $pid
sed -i '$i\ <entry key="secureConnections" value="false"/>' /home/user/.java/.userPrefs/es/gob/afirma/standalone/ui/preferences/prefs.xml
sed -i '$i\ <entry key="omitAskOnClose" value="true"/>' /home/user/.java/.userPrefs/es/gob/afirma/standalone/ui/preferences/prefs.xml
